name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

jobs:
  build:
    name: Build Exp
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        
      - name: Build Exp Release
        env:
            SKETCHUB_API_KEY: ${{ secrets.SKETCHUB_API_KEY }}
        run: ./gradlew assembleRelease

      - name: Upload release app
        uses: actions/upload-artifact@v4
        with:
          name: exp-release
          path: composeApp/build/outputs/apk/release/