name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

jobs:
  build-sample:
    strategy:
      matrix:
        config: [
          { target: android, os: ubuntu-latest, tasks: assembleDebug, continueOnError: false },
          { target: iOS, os: macos-latest, tasks: compileKotlinIosArm64 compileKotlinIosX64 compileKotlinIosSimulatorArm64, continueOnError: false },
          { target: desktop, os: ubuntu-latest, tasks: compileKotlinDesktop, continueOnError: false }
        ]
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Build sample ${{ matrix.config.target }} - Main
        continue-on-error: ${{ matrix.config.continueOnError }}
        run: ./gradlew :composeApp:${{ matrix.config.tasks }}